config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'vacations#index'

  resources :users do
    resources :vacations, only: %i[index new create], shallow: true
  end

  namespace :admin do
    resources :vacations, only: %i[index update]
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, :last_name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable
  has_many :vacations, dependent: :destroy

  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
end

app/models/vacation.rb
class Vacation < ApplicationRecord
  STATUSES = %W[Unconfirmed Confirmed Declined].freeze
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, inclusion: { in: STATUSES }
  belongs_to :user

  validate :end_date_before_start_date

  private

  def end_date_before_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, 'должна быть после даты начала отпуска')
    end
  end
end

app/controllers/Admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'

  before_action :authenticate_user!
  before_action :admin_required!

  private

  def admin_required!
    redirect_to root_path, alert: 'Вы не можете просматривать содержимое этой страницы!' unless current_user.is_a?(Admin)
  end
end

app/controllers/Admin/vacations_controller.rb
class Admin::VacationsController < Admin::BaseController
  before_action :vacation_params, only: :update
  def index
    @vacations = Vacation.all
  end

  def update
    @vacation = Vacation.find(params[:id])
    if @vacation.update(vacation_params)
      if @vacation.status == "Confirmed"
        VacationStatusMailer.approved_status(@vacation).deliver_now
      elsif @vacation.status == "Declined"
        VacationStatusMailer.declined_status(@vacation).deliver_now
      end
      redirect_to admin_vacations_path, notice: "Status updated successfully"
    else
      flash[:error] = "Failed to update status"
    end
  end

  private

  def vacation_params
    params.require(:vacation).permit(:start_date, :end_date, :status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :first_name, :last_name, :password, :password_confirmation])
  end
end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    user_id = @user.id
    @vacations = @user.vacations
  end

  def show; end

  def new
    @vacation = Vacation.new
  end

  def create
    @vacation = current_user.vacations.build(vacation_params)

    if @vacation.save
      redirect_to user_vacations_path(current_user), notice: 'Request created'
    else
      render :new
    end
  end

  private

  def vacation_params
    params.require(:vacation).permit(:start_date, :end_date)
  end
end

app/helpers/admin/vacations_helper.rb
module Admin::VacationsHelper
  def statuses
    Vacation::STATUSES.map { |status | [t("vacation.statuses.#{status}"), status] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_admin?
    current_user.is_a?(Admin)
  end
end

app/helpers/vacation_helper.rb
module VacationHelper
end

app/views/admin/_nav.html.slim
- if user_signed_in?
  h1 Admin
  = current_user.email
  p
  = form_tag destroy_user_session_path, method: :delete do
    = submit_tag "Sign out"
    end

app/views/admin/vacations/edit.html.slim
p @vacations

app/views/admin/vacations/index.html.slim
- @vacations.group_by(&:user).each do |user, vacations|
  h3 = "User: #{user.first_name}"
  ul
    - vacations.each do |vacation|
      li
        = vacation.start_date
        | -
        = vacation.end_date
        | Status:
        = form_with model: [:admin, vacation], method: :patch do |f|
          = f.label :status
          = f.select :status, statuses, prompt: 'Select status'
          = f.submit 'Update'

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin Panel | VacationsPlanner</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= render 'admin/nav' %>
  <%= render 'shared/flash' %>
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.slim
 - if resource&&resource.errors.present?
   b= "#{resource.errors.count} error(s) detected: "
   ul
     -resource.errors.full_messages.each do |message|
       li= message

app/views/shared/_flash.html.slim
- if flash.any?
  .flash-messages
    - flash.each do |type, message|
      div class="flash-message flash-#{type}"
        = message

app/views/shared/_navbar.html.slim
- if user_signed_in?
  = current_user.email
  p
  = form_tag destroy_user_session_path, method: :delete do
    = submit_tag "Sign out"
    end
  - if is_admin?
    = link_to ' | Administrative side', admin_vacations_path
  - else
    = link_to ' | Main', user_vacations_path(current_user.id)
    = link_to ' | New', new_user_vacation_path(current_user.id)

app/views/vacations/index.html.slim
= render 'shared/navbar'
h1 #{@user.first_name}'s Vacations

ul
  - @vacations.each do |vacation|
    li
      = vacation.start_date
      | -
      = vacation.end_date

      = vacation.status

app/views/vacations/new.html.slim
- if user_signed_in?
  = render 'shared/errors', resource: @vacation
  = link_to ' | Main', user_vacations_path(current_user.id)

  = form_with model: [current_user, @vacation] do |f|
    = f.label :start_date
    = f.date_field :start_date

    = f.label :end_date
    = f.date_field :end_date

    = f.submit 'Create vacation'
- else
  = link_to "Log in", new_user_session_path